apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  database_url: postgresql+psycopg2://postgres:postgres@photo-postgres:5432/photo_platform
  jwt_secret: JWT_SECRET
  admin_email: admin@photoclassify.com
  admin_password: admin123
  db_user: postgres
  db_password: postgres
